### ISSUE TITLE
json.loads failing to detect encoding under python3.5

### ISSUE THREAD

**Issue by pennytacos** [kismetwireless/python-kismet-rest#2]
under ubuntu 16.04 (vendor repo hosts python 3.5.2 as latest version) encountered error:
```
Traceback (most recent call last):
  File "./wifi-alarm.py", line 38, in <module>
    for device in devices.by_mac(devices=macs, fields=fields):
  File "/usr/local/lib/python3.5/dist-packages/kismet_rest/devices.py", line 62, in by_mac
    for result in self.interact_yield("POST", url, **call_settings):
  File "/usr/local/lib/python3.5/dist-packages/kismet_rest/base_interface.py", line 255, in interact_yield
    for result in self.process_response_stream(response, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/kismet_rest/base_interface.py", line 271, in process_response_stream
    yield json.loads(result)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
````

upgrade to python 3.6.8 solves.

other work arounds seem to be:
- adding "; charset=utf8" to RegisterMimeType string for json and ekjson in  kis_net_microhttpd.cc 
- setting response.encoding to 'utf-8' and calling response.iter_lines(decode_unicode=True) in affected function in base_interface.py (obviously would need to be added in other places as well)

i don't know if support for python 3.5 is a concern but i figured i would put the info out there.

**Comment by ashmastaflash** [comment]
Hey @pennytacos  
Great issue write-up. Try the code in the issue/2 branch (https://github.com/kismetwireless/python-kismet-rest/tree/issue/2) and let me know if that works for you.

**Comment by pennytacos** [comment]
@ashmastaflash the changes in that branch runs on python 3.5.2 with out error.

thanks quick response and for the fix.
